# Generated by Django 4.2.16 on 2024-09-22 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_lesson_video_url_lesson_video_file_and_more'),
    ]

    operations = [
        
    ]
