# Generated by Django 4.2.16 on 2024-09-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/instructor'),
        ),
    ]
