# Generated by Django 4.2.16 on 2024-09-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_lesson_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media/thumbnails/'),
        ),
    ]
