# Generated by Django 4.2.16 on 2024-09-15 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_unique_user_profile'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='profile',
            name='unique_user_profile',
        ),
    ]
