# Generated by Django 4.2.16 on 2024-09-15 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landpage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
